# Cloud Build設定
# トリガーからの自動デプロイ、または手動デプロイ用

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/adpilot:latest'
      - '.'

  # Container Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/adpilot:latest'

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'adpilot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/adpilot:latest'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--set-env-vars'
      - 'AUTH_SECRET=cY0UdD3b0nuBT0XT9n9yyCEhdpwzFhgh9Wc5QIBr3n4=,NEXTAUTH_URL=https://adpilot-hbkw5vdvuq-an.a.run.app,NEXTAUTH_SECRET=cY0UdD3b0nuBT0XT9n9yyCEhdpwzFhgh9Wc5QIBr3n4='
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,CHATWORK_API_TOKEN=CHATWORK_API_TOKEN:latest,CHATWORK_ROOM_ID=CHATWORK_ROOM_ID:latest,CHATWORK_ERROR_ROOM_ID=CHATWORK_ERROR_ROOM_ID:latest,GOOGLE_SHEETS_CLIENT_EMAIL=GOOGLE_SHEETS_CLIENT_EMAIL:latest,GOOGLE_SHEETS_PRIVATE_KEY=GOOGLE_SHEETS_PRIVATE_KEY:latest,GOOGLE_SHEETS_SPREADSHEET_ID=GOOGLE_SHEETS_SPREADSHEET_ID:latest,GOOGLE_SHEETS_HISTORICAL_SPREADSHEET_ID=GOOGLE_SHEETS_HISTORICAL_SPREADSHEET_ID:latest,META_ACCESS_TOKEN=META_ACCESS_TOKEN:latest,TIKTOK_ACCESS_TOKEN=TIKTOK_ACCESS_TOKEN:latest,TIKTOK_ADVERTISER_IDS=TIKTOK_ADVERTISER_IDS:latest,META_TOKEN_BUSINESS01=META_TOKEN_BUSINESS01:latest,META_TOKEN_BUSINESS03=META_TOKEN_BUSINESS03:latest,META_TOKEN_BUSINESS08=META_TOKEN_BUSINESS08:latest,META_TOKEN_BUSINESS11=META_TOKEN_BUSINESS11:latest,META_TOKEN_BUSINESS13=META_TOKEN_BUSINESS13:latest,META_TOKEN_BUSINESS14=META_TOKEN_BUSINESS14:latest'

images:
  - 'gcr.io/$PROJECT_ID/adpilot:latest'

timeout: '1200s'

